### ISSUE TITLE
Missing dist folder

### ISSUE THREAD

**Issue by sksksksk** [heiseonline/embetty#14]
### General information

- `embetty` version: 1.0.4
- Operating system name and version: ubuntu 16.04
- Browser name and version: Opera 53

### Steps to reproduce the behaviour

I downloaded 1.0.4 from the release page and tried to follow the instructions (option 1) to setup a sample page.
There is no ./dist/embetty.js that is mentioned in the docs.
Including ./lib/embetty.js results in "Uncaught SyntaxError: Unexpected string" in opera + chrome. So the ./lib/embetty.js is obviously not the correct one.

The example pages reference a embetty.js that is also not available. 

I did not try the other 2 options as I do not have a suitable dev environment.

So what am I missing?

**Comment by compeak** [comment]
@sksksksk Thank you for reporting this bug.

We forgot to deploy the build artifacts to GitHub. This should be fixed in [v1.0.5](https://github.com/heiseonline/embetty/releases/tag/1.0.5).

**Comment by sksksksk** [comment]
thanks for the quick response. 

But I'm afraid that I still don't see the embetty.js file I have to include in my page (downloaded 1.0.5).

There still is not dist folder, and the only embetty.js file is in lib and in test folder, which both produce JS errors

**Comment by compeak** [comment]
> There still is not dist folder

@sksksksk The path mentioned in the readme was wrong. I fixed that yesterday after releasing 1.0.5.

> There still is not dist folder, and the only embetty.js file is in lib and in test folder, which both produce JS errors

@sksksksk Please download [the release files](https://github.com/heiseonline/embetty/releases/tag/1.0.5), not the copy of the repository provided by GitHub:

![release-files](https://user-images.githubusercontent.com/1942208/40640355-f1f7b134-6315-11e8-8e04-8cf517766e0e.png)

There is a prebuilt `embetty.js` included:

![screen shot 2018-05-29 at 07 57 56](https://user-images.githubusercontent.com/1942208/40640401-298471dc-6316-11e8-8bba-fb8f07afbd0a.png)

**Comment by sksksksk** [comment]
it worked not. Thanks!

**Comment by compeak** [comment]
> it worked not. Thanks!

@sksksksk What?

Please close this issue if the problem has been solved.

**Comment by sksksksk** [comment]
I am really really sorry: it should have been "it worked **now**"
